### ISSUE TITLE
unicode: incorrect dump of header's data parsed in human-readable format when pool layout is unicode encoded

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#552] opened 2017-05-29 09:25 UTC
Consider following flow:
```
pmempool create obj -l 🐀🐁 mypool
pmempool info -x mypool
```
The output is:

> Part file:
> path                     : mypool
> type                     : regular file
> size                     : 8388608
> 
> POOL Header:
> 00000000  50 4d 45 4d 4f 42 4a 00  03 00 00 00 00 00 00 00  |PMEMOBJ.........|
> 00000010  00 00 00 00 00 00 00 00  a2 19 5e 18 10 08 4e 44  |..........^...ND|
> 00000020  82 bf 1f 7d d2 8d 02 5b  30 1a 07 40 2b 59 a0 47  |...}...[0..@+Y.G|
> 00000030  bd f3 79 3e 44 94 8a 85  30 1a 07 40 2b 59 a0 47  |..y>D...0..@+Y.G|
> 
> 00000070  bd f3 79 3e 44 94 8a 85  f5 9d 1d 59 00 00 00 00  |..y>D......Y....|
> 00000080  10 33 77 37 77 07 00 00  02 01 00 00 00 00 3e 00  |.3w7w.........>.|
> 00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 
> ------------------------------------------------------------------------------
> Signature                : PMEMOBJ
> Major                    : 3
> Mandatory features       : 0x0
> Not mandatory features   : 0x0
> Forced RO                : 0x0
> Pool set UUID            : 185e19a2-0810-444e-82bf-1f7dd28d025b
> UUID                     : 40071a30-592b-47a0-bdf3-793e44948a85
> Previous part UUID       : 40071a30-592b-47a0-bdf3-793e44948a85
> Next part UUID           : 40071a30-592b-47a0-bdf3-793e44948a85
> Previous replica UUID    : 40071a30-592b-47a0-bdf3-793e44948a85
> Next replica UUID        : 40071a30-592b-47a0-bdf3-793e44948a85
> Creation Time            : Thu May 18 2017 15:13:25
> Alignment Descriptor     : 0x0000077737773310[OK]
> Class                    : ELF64
> Data                     : 2's complement, little endian
> Machine                  : AMD X86-64
> Checksum                 : 0xf8f96c1f8d8cc0f2 [OK]
> 
> PMEM OBJ Header:
> 00001000  f0 9f 90 80 f0 9f 90 81  00 00 00 00 00 00 00 00  |................|
> 00001010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 
> 00001400  00 20 00 00 00 00 00 00  00 04 00 00 00 00 00 00  |. ..............|
> 00001410  00 20 30 00 00 00 00 00  00 e0 4f 00 00 00 00 00  |. 0.......O.....|
> 00001420  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 
> 00017f0  00 00 00 00 00 00 00 00  e0 63 a1 02 10 58 73 3e  |.........c...Xs>|
> 00001800  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00  |................|
> 00001810  00 00 00 00 00 00 00 00  00 00 40 dd 2c 00 00 00  |..........@.,...|
> 00001820  00 00 80 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 00001830  80 03 c5 23 f7 7f 00 00  a0 00 c5 23 f7 7f 00 00  |...#.......#....|
> 00001840  f0 ff c4 23 f7 7f 00 00  80 01 c5 23 f7 7f 00 00  |...#.......#....|
> 00001850  80 02 c5 23 f7 7f 00 00  00 00 40 dd 2c 00 00 00  |...#......@.,...|
> 00001860  00 00 80 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 00001870  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 00001880  00 20 70 dd 2c 00 00 00  00 00 00 00 00 00 00 00  |. p.,...........|
> 00001890  00 e0 4f 00 00 00 00 00  02 00 00 00 00 00 00 00  |..O.............|
> 000018a0  00 00 40 dd 2c 00 00 00  00 04 00 00 00 00 00 00  |..@.,...........|
> 000018b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 000018c0  1f 4c 85 c2 65 41 a6 20  00 00 00 00 00 00 00 00  |.L..eA. ........|
> 000018d0  a0 05 a9 db 2c 00 00 00  a0 78 a8 db 2c 00 00 00  |....,....x..,...|
> 000018e0  00 00 00 00 00 00 00 00  10 84 a8 db 2c 00 00 00  |............,...|
> 000018f0  bc a2 c2 23 f7 7f 00 00  bc a2 c2 23 f7 7f 00 00  |...#.......#....|
> 00001900  90 f9 c4 23 f7 7f 00 00  f0 fd c4 23 f7 7f 00 00  |...#.......#....|
> 00001910  f0 fe c4 23 f7 7f 00 00  80 03 c5 23 f7 7f 00 00  |...#.......#....|
> 00001920  a0 00 c5 23 f7 7f 00 00  f0 ff c4 23 f7 7f 00 00  |...#.......#....|
> 00001930  80 01 c5 23 f7 7f 00 00  80 02 c5 23 f7 7f 00 00  |...#.......#....|
> 00001940  00 00 40 dd 2c 00 00 00  00 00 80 00 00 00 00 00  |..@.,...........|
> 00001950  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 
> 000019a0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00  |................|
> 000019b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 
> 000019e0  d0 2d a8 db 2c 00 00 00  00 00 00 00 00 00 00 00  |.-..,...........|
> 000019f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> 
> ------------------------------------------------------------------------------
> Layout                   : 🐀🐁
> Lanes offset             : 0x2000
> Number of lanes          : 1024
> Heap offset              : 0x302000
> Heap size                : 5234688
> Checksum                 : 0x3e73581002a163e0 [OK]
> Root offset              : 0x0

There is no layout viewed in human readable headers data.
When creating obj pool with ANSI layout (ie "mylayout"), it is shown as follows:

> ...
> PMEM OBJ Header:
> 00001000  6d 79 6c 61 79 6f 75 74  00 00 00 00 00 00 00 00  |mylayout........|
> ...

Found on:  1.2+b1-403-g5d3437c

**Comment by krzycz** [comment] 2017-05-29 10:20
Layout **is** printed in human readable format, as seen in the log above:
> Layout : 🐀🐁
> Lanes offset : 0x2000
> ...

However, in the hex dump of the header, UTF-8 encoded string cannot be printed, as:
1) each character is encoded with more than one byte;
2) all the characters (bytes) of values >= 0x80 ("f0 9f 90 80 f0 9f 90 81") are assumed non-printable and represented by dots ".".

Closing as not a bug.

**Closed by krzycz** 2017-05-29 10:20 UTC
Labels: Exposure: Low, OS: Linux, OS: Windows, Priority: 3 medium
