### ISSUE TITLE
unit test: obj_pmalloc_mt Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)

### ISSUE THREAD

**Issue by daixiang0** [pmem/issues#573] opened 2017-06-09 01:00 UTC
WIth nvml commit: 6a599dffa324d0ed5a34cebff6271587cf5f9cb1
It occur again:
```
root@lkp-hsw-ep4 /lkp/benchmarks/nvml-unit-tests/src/test# ./RUNTESTS -f pmem obj_pmalloc_mt -s TEST1
obj_pmalloc_mt/TEST1: SETUP (check/pmem/debug)
obj_pmalloc_mt/TEST1: START: obj_pmalloc_mt
obj_pmalloc_mt/TEST1 crashed (signal 6). err1.log below.
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:198 ut_sighandler} {obj_pmalloc_mt.c:151 alloc_free_worker} {ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: 

obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{obj_pmalloc_mt.c:151 alloc_free_worker} {ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
{obj_pmalloc_mt.c:151 alloc_free_worker} obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{obj_pmalloc_mt.c:151 alloc_free_worker} {ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
obj_pmalloc_mt/TEST1: Error: assertion failure: err (0xffffffffffffffff) == 0 (0x0)
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 0: ./obj_pmalloc_mt() [0x441fdc]
{ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:199 ut_sighandler} {ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: Signal 6, backtrace:
obj_pmalloc_mt/TEST1: 1: ./obj_pmalloc_mt() [0x44211b]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 2: /lib/x86_64-linux-gnu/libc.so.6(+0x33030) [0x7fe4f0006030]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 3: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fe4f0005fcf]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 4: /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fe4f00073fa]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 5: ./obj_pmalloc_mt() [0x43efb5]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 6: ./obj_pmalloc_mt() [0x404735]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 7: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7fe4f0379494]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 8: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fe4f00bbaff]
{ut_backtrace.c:201 ut_sighandler} obj_pmalloc_mt/TEST1: 

{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 0: ./obj_pmalloc_mt() [0x441fdc]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 1: ./obj_pmalloc_mt() [0x44211b]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 2: /lib/x86_64-linux-gnu/libc.so.6(+0x33030) [0x7fe4f0006030]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 3: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fe4f0005fcf]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 4: /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fe4f00073fa]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 5: ./obj_pmalloc_mt() [0x43efb5]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 6: ./obj_pmalloc_mt() [0x404735]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 7: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7fe4f0379494]
{ut_backtrace.c:149 ut_dump_backtrace} obj_pmalloc_mt/TEST1: 8: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fe4f00bbaff]
{ut_backtrace.c:201 ut_sighandler} obj_pmalloc_mt/TEST1: 

out1.log below.
obj_pmalloc_mt/TEST1 out1.log obj_pmalloc_mt/TEST1: START: obj_pmalloc_mt
obj_pmalloc_mt/TEST1 out1.log  ./obj_pmalloc_mt /fs/pmem0//test_obj_pmalloc_mt1😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋/testfile

pmem1.log below.
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <1> [out.c:261 out_init] pid 4479: program: /lkp/benchmarks/nvml-unit-tests/src/test/obj_pmalloc_mt/obj_pmalloc_mt
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <1> [out.c:263 out_init] libpmem version 1.0
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <1> [out.c:264 out_init] src version SRCVERSION:1.2+b1-491-g6a599dffa324
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <1> [out.c:272 out_init] compiled with support for Valgrind pmemcheck
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <1> [out.c:277 out_init] compiled with support for Valgrind helgrind
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <1> [out.c:282 out_init] compiled with support for Valgrind memcheck
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <1> [out.c:287 out_init] compiled with support for Valgrind drd
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [mmap.c:91 util_mmap_init] 
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [libpmem.c:56 libpmem_init] 
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1254 pmem_init] 
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1216 pmem_get_cpuinfo] 
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1220 pmem_get_cpuinfo] clflush supported
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1189 pmem_log_cpuinfo] 
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1196 pmem_log_cpuinfo] using clflush
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1203 pmem_log_cpuinfo] using movnt
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:476 pmem_is_pmem_init] 
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:441 is_pmem_always] addr 0x7fe4f0bc6000 len 4096
obj_pmalloc_mt/TEST1 pmem1.log <libpmem>: <3> [pmem.c:441 is_pmem_always] addr 0x7fe4ede00000 len 33554432

Last 30 lines of pmemobj1.log below (whole file has 12705 lines).
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4b3ffeeb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1949 constructor_alloc_bytype] pop 0x7fe4ede00000 ptr 0x7fe4ef0c1910 arg 0x7fe4b3ffed60
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2341 pmemobj_free] oid.off 0x00000000012c1910
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1892 pmemobj_pool_by_oid] oid.off 0x00000000012c1910
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4b3ffeeb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1949 constructor_alloc_bytype] pop 0x7fe4ede00000 ptr 0x7fe4ef0c19d0 arg 0x7fe4b3ffed60
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1892 pmemobj_pool_by_oid] oid.off 0x0000000001e416d0
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2341 pmemobj_free] oid.off 0x00000000012c19d0
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1892 pmemobj_pool_by_oid] oid.off 0x00000000012c19d0
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4b3ffeeb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2341 pmemobj_free] oid.off 0x0000000000e81b50
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4ebdfaeb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1892 pmemobj_pool_by_oid] oid.off 0x0000000000e81b50
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4b8ff8eb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4b8ff8eb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1949 constructor_alloc_bytype] pop 0x7fe4ede00000 ptr 0x7fe4ef0c1a90 arg 0x7fe4b3ffed60
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4eddfeeb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:1892 pmemobj_pool_by_oid] oid.off 0x0000000001041790
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2341 pmemobj_free] oid.off 0x0000000001381a90
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:2016 pmemobj_alloc] pop 0x7fe4ede00000 oidp 0x7fe4eb5f9eb0 size 104 type_num 0 constructor (nil) arg (nil)
obj_pmalloc_mt/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 

RUNTESTS: stopping: obj_pmalloc_mt/TEST1 failed, TEST=check FS=pmem BUILD=debug
```
Since the PMEM is just created by mount -t dax?
My config is as below:
```
root@lkp-hsw-ep4 /lkp/benchmarks/nvml-unit-tests/src/test# cat testconfig.sh
PMEM_FS_DIR=/fs/pmem0 <=== just monut -o dax to create
NODE[0]=127.0.0.1
NODE_WORKING_DIR[0]=/lkp/benchmarks/nvml-unit-tests/src/test
NODE[1]=127.0.0.1
NODE_WORKING_DIR[1]=/lkp/benchmarks/nvml-unit-tests/src/test
NODE[2]=127.0.0.1
NODE_WORKING_DIR[2]=/lkp/benchmarks/nvml-unit-tests/src/test
NODE[3]=127.0.0.1
NODE_WORKING_DIR[3]=/lkp/benchmarks/nvml-unit-tests/src/test
RPMEM_VALGRIND_ENABLED=y
PMEM_FS_DIR_FORCE_PMEM=1
```

**Comment by pbalcer** [comment] 2017-06-09 08:37
Duplicate of #564. I'm going to close this one. We have a patch almost ready.

**Closed by pbalcer** 2017-06-09 08:37 UTC

**Comment by daixiang0** [comment] 2017-06-12 05:40
Thanks.
