### ISSUE TITLE
libpmemobj C++ tests do not compile on Fedora 24 and 25 (rawhide)

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#189] opened 2016-06-26 06:38 UTC
NVML compilation fails with **gcc 6.1.1**
Observed on release: **1.1-rc3**

```
make -C obj_cpp_ptr all
make[3]: Entering directory '/builddir/build/BUILD/nvml-1.1/src/test/obj_cpp_ptr'
g++ -MD -c -std=c++11 -ggdb -ggdb -Wall -Werror -Wpointer-arith -Wunused-macros -fno-common  -I../unittest -I../../../src/../src/include obj_cpp_ptr.cpp -o obj_cpp_ptr.o
In file included from obj_cpp_ptr.cpp:38:0:
obj_cpp_ptr.cpp: In lambda function:
obj_cpp_ptr.cpp:171:15: internal compiler error: in make_decl_rtl, at varasm.c:1299
    UT_ASSERT(r->pfoo == nullptr);
               ^
../unittest/unittest.h:181:55: note: in definition of macro 'UT_COMPILE_ERROR_ON'
 #define UT_COMPILE_ERROR_ON(cond) ((void)sizeof(char[(cond) ? -1 : 1]))
                                                       ^~~~
../unittest/unittest.h:224:4: note: in expansion of macro 'UT_ASSERT_COMPILE_ERROR_ON'
    UT_ASSERT_COMPILE_ERROR_ON(cnd);\
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
obj_cpp_ptr.cpp:171:4: note: in expansion of macro 'UT_ASSERT'
    UT_ASSERT(r->pfoo == nullptr);
    ^~~~~~~~~
```

Full log: http://koji.fedoraproject.org/koji/watchlogs?taskID=14648157

**Comment by krzycz** [comment] 2016-06-26 20:45
Workaround merged to master. Not a blocker for 1.1 release.

**Comment by tomaszkapela** [comment] 2016-06-27 14:57
This is an ICE and it has to do with us using lambda expressions. If you change the `transaction::exec_tx` call to `transaction::manual`, the test compiles fine. There is a bug issued for the exact same line in GCC (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67737), but the root cause seems different. I say we mark this bug as external and monitor the situation. We could also look into a better workaround/solution, but this is not an issue with our code.

**Comment by plebioda** [comment] 2016-11-15 18:20
@krzycz Can we close it ? If not do we really need to fix this for 1.2 ?

**Comment by krzycz** [comment] 2016-11-15 18:59
It's an external bug, so we don't need a fix for it.
Perhaps we should verify if this w/a is still required on Fedora or if gcc has been already fixed. For the latter, we could remove the workaround. But it's not needed for 1.2.

**Comment by krzycz** [comment] 2016-11-28 11:58
The workaround is still required for Fedora 26.

**Comment by kilobyte** [comment] 2019-09-23 15:30
The gcc bug has been long fixed, any versions of Fedora which had it are long since EOLed.  The only platform that has such ancient version of gcc is RHEL 7, which we have mostly dropped support for in CPP for similar reasons (ie, a backported compiler is required).

**Closed by kilobyte** 2019-09-23 15:30 UTC
Labels: Exposure: Low, Priority: 3 medium, Type: External Bug
