### ISSUE TITLE
obj: pmemobj_open() and pmemobj_create() are not thread-safe

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#228] opened 2016-09-06 10:51 UTC
It's not safe to do multiple calls to _pmemobj_open_ or _pmemobj_create_ simultaneously in a multi-threaded program (to open/create multiple pmemobj pools).  It is unlikely that any program would do that, but it should be fixed anyway, or at least clearly described in man pages.

**Comment by pbalcer** [comment] 2016-09-09 13:22
It's described in the tutorial page:
http://pmem.io/2015/06/18/threads.html

We should update the page if the behavior is changed.

**Comment by GBuella** [comment] 2017-10-12 15:40
Note: both pmemfile, and pmemkv might open pools while other threads are accessing other pools.

**Comment by marcinslusarz** [comment] 2018-07-12 16:19
Duplicate of #872 (it was created later, but it has better description).

Closing this one.

**Closed by marcinslusarz** 2018-07-12 16:19 UTC
Labels: Exposure: Low, Priority: 3 medium, Type: Feature
