### ISSUE TITLE
vmem: vmem_set_funcs work partially

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#47] opened 2015-03-31 10:58 UTC
vmem_set_funcs overrides only print function. Does not work with malloc, free, realloc, and strdup.

steps to reproduce:
1) try override function (malloc, free, realloc, strdup) with own implementation
2) verify if proper function was called

expected result:
API should use overridden function instead of default

current result:
default function is called

**Comment by marcinslusarz** [comment] 2015-09-14 09:47
set_funcs test indicates it's working - vmem_create + vmem_delete does one allocation and one deallocation using passed function pointers. Can you double check on 0.3-rc2 and if it's still not working explain how did you test this?

**Comment by kkajrewicz** [comment] 2015-11-13 15:34
Our steps are:
1) Define global 'is_overriden' var (that is false)
2) define own malloc/free/realloc function that calls appropriate function from standard library and sets global var to true
3) override default function calling vmem_set_funcs with proper arg
4) call vmem_malloc/vmem_free/vmem_realloc
5) check if global var is set to true

git describe: 0.3+b3-142-g6088956

**Comment by plebioda** [comment] 2015-11-13 16:05
If I understand you correctly you expect that every call to vmem_malloc/vmem_free/vmem_realloc will internally call the malloc/free/realloc, which we would like to override. Actually this it is NOT true. Using vmem_set_funcs we can override *internal* allocator. The internal allocator is used only in some cases and not necessary during every vmem_malloc/vmem_free/vmem_realloc call.

I think that this is not an issue and we can close it.

**Comment by krzycz** [comment] 2015-11-13 18:20
In the existing implementation, *libvmem* does not make any use of *realloc* nor *strdup* internally, and overriding those two interfaces using *vmem_set_funcs* has no effect.  This may be subject to change in the future, so for this reason, and for the sake of uniformity with other NVM libraries, we keep this API as is.
Also, the user must not expect that overriding malloc functions with *vmem_set_funcs* will affect all the allocations made by the program, but only those made internally by *libvmem* to allocate its metadata.

In practice, it's not trivial to design the tests for this feature.  However, one of the upcoming patches will affect the usage of the internal allocator. Some thread-specific date will be allocated on the first call to *vmem_malloc* in given thread, and possibly reallocated when more pools are created.  These allocations will be free'd when the thread completes, or (for the main thread) in the library destructor.  Seems like with this change, the best test for *vmem_set_func* would be to spawn multiple threads and do at least one allocation in each thread. This should trigger multiple calls to custom malloc/free, if configured.

Anyway, current behavior is not a bug - this feature just requires more sophisticated test.

**Comment by kkajrewicz** [comment] 2015-11-26 11:28
Verified on 0.4-rc1-18-g9ad12cd

**Closed by kkajrewicz** 2015-11-26 11:28 UTC
Labels: Exposure: Medium, Priority: 3 medium, Type: Bug
