### ISSUE TITLE
win: pmem_unmap succedes for addresses outside the valid scope

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#227] opened 2016-09-02 07:58 UTC
pmem_unmap returns 0 for len parameter in range [max(size_t) - 64 kb, max(size_t)] which is outside of valid space.

 Found on: 1.1-460-gf0491bb

**Comment by kasiawasiuta** [comment] 2016-09-08 07:57
Still an issue 1.1-506-gf479eb0

**Comment by krzycz** [comment] 2016-11-04 17:42
According to munmap() documentation (http://man7.org/linux/man-pages/man2/mmap.2.html):
"It is not an error if the indicated range does not contain any mapped pages."
Some versions of munmap() man pages also say that EINVAL may be set if "Addresses in the range [addr,addr+len) are outside the valid range for the address space of a process." So, this might be the case of `len == SIZE_MAX`. 
However in practice, the behavior of munmap() fed with invalid arguments is undefined - it may be different depending on the start address and the process memory map on given OS. I.e. by providing a fairly large "len" you may unmap some critical regions of process memory (i.e. stack), which would result in SEGFAULT rather than an error.

IMHO, there is no value in testing such scenario, as you can't expect any deterministic results. I'd suggest to remove this test case.

Closing as "not a bug".

**Closed by krzycz** 2016-11-04 17:42 UTC
Labels: Exposure: Medium, Priority: 3 medium, Type: Bug
