### ISSUE TITLE
vmem: memory reallocation to size less than actual returns NULL pointer

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#24] opened 2015-01-20 13:49 UTC
Memory reallocation to size less than actual, returns NULL pointer. In general when sum of already allocated memory and desired memory size is bigger than usable pool size, then NULL pointer is returned.

Steps to reproduce:
1. create valid vmem pool: vmp = vmem_create("/mnt/psmem", VMEM_MIN_POOL);
2. allocate memory: ptr1 = vmem_malloc(vmp, 8 * 1024 * 1024);
3. shrink the memory block: ptr2 = vmem_realloc(vmp, ptr1, 1);

Expected result:
Valid memory pointer should be returned;

Actual result: 
NULL pointer is returned;

**Comment by pbalcer** [comment] 2015-01-20 14:15
I'm not sure if this is an issue... the allocator does not gives any guarantees on what it is going to do when in this OOM corner case, it's an implementation detail. According to C99 standard:
>The realloc function returns a pointer to the new object (which **may** have the same value as a pointer to the old object), or a null pointer if the new object could not be allocated. 
notice the emphasis.

**Comment by krzycz** [comment] 2015-01-20 19:16
That's true, but if the new size is less than the current size, there is no point in allocating new block of memory and copying data to the new buffer. Why not just reuse the existing buffer (if possible)?

On the other hand, in given scenario, the **huge** buffer is resized to the **small** one. This requires a new chunk (4MB) for a new run of small buffers, and this is probably the root cause of the problem. I believe that reallocation of 8MB buffer to the new size of 6MB, 4MB, 3MB, or even 2MB, would work.

**Comment by donaldematthews** [comment] 2015-02-10 03:28
You are correct, reallocation of the 8 MB buffer to a new size of 6 MB works, as does 5 MB.  But with a new size of 4 MB or less, the reallocation fails.  The pool size is VMEM_MIN_POOL, which equates to 14 MB, so I'm curious why a reallocation of 4 MB (or less) fails.  It seems that it should be possible for a huge buffer to be re-sized to a small one, even if it does require a new 4 MB chunk.

But it does fail, and debugging this a bit, chunk_recycle (in src/jemalloc/src/chunk.c) returns NULL.  It gets back a NULL node from extent_tree_szad_nsearch.

**Comment by donaldematthews** [comment] 2015-02-11 02:51
My testing so far reveals that the realloc operation works when using standard malloc/realloc, executing my test app as follows:

./vmem_realloc_test

It also works when using vanilla jemalloc, executing my test app as follows:

LD_PRELOAD=/usr/lib64/libjemalloc.so.1 ./vmem_realloc_test

But it fails when using vmem_malloc/vmem_realloc.

Debugging this a bit, chunk_recycle (in nvml/src/jemalloc/src/chunk.c) returns NULL.  It gets back a NULL node from extent_tree_szad_nsearch.  Hope this helps.

**Comment by krzycz** [comment] 2015-02-12 15:01
IMHO there is no point in testing such scenario with standard malloc (libc), nor with vanilla jemalloc.
Those libraries are not limited by pool (file) size, so it's almost impossible to reach out-of-memory condition.

For me, this issue is similar to this one: pmem/issues#25. Basically, it seems like to perform realloc, the library (jemalloc) needs to allocate something, even if the new allocation size is smaller than the old one. 

Since jemalloc operates on 4MB chunks, then 8MB allocation requires 2 * 4MB, but 6MB also requires 2 * 4MB (though, 2MB is wasted). So, in practice, nothing happens.
The interesting case is when we reallocate from 8MB to 4MB. In theory, the library can simply release the second 4MB chunk, leaving the first chunk untouched, and return the original pointer. Seems like there is no need to allocate anything, but...
... the released chunk is stored in an extent chunk tree (for future reuse), so there must be a new node allocated and inserted into the tree. And probably the allocation of the new node fails, causing the actual realloc failure.

**Comment by paul-von-behren** [comment] 2015-02-12 15:28
I suggested testing with realloc (libc) as a way to determine what the appropriate behavior should be for this test case; perhaps the reported behavior is by design.  The man page description of vmem_realloc() starts with: "The vmem_realloc() function provides the same semantics as realloc(3),  but  operates  on  the  memory  pool vmp instead of the process heap supplied by the system." This test case shows that in this case, we're not providing the same semantics as realloc.  I also suggested testing with jemalloc to verify that this quirk was something vmem introduces and not a latent quirk from jemalloc.  I don't see a need to run these tests again; just the once to verify that this is (as expected) something we need to address in vmem.

**Comment by krzycz** [comment] 2015-02-20 13:44
Seems like I was wrong. Realloc from 8MB to 4MB (or to 2MB, 1MB) doesn't work as I was thinking.
If the new size requires less chunks (2 vs.1 in this case), then new chunks are allocated and the data is copied from the old buffer to the new one. :disappointed: 
This has been addressed already: https://github.com/jemalloc/jemalloc/commit/f8034540a16a6f4fc7948e4783747ca1e9055823
But the version of *jemallloc* we are using does not include this patch, of course.

**Comment by krzycz** [comment] 2015-02-20 13:47
See also: https://github.com/jemalloc/jemalloc/commit/a95018ee819abf897562d9d1f3bc31d4dd725a8d

**Comment by marcinslusarz** [comment] 2015-06-22 07:47
Both patches were merged. Please verify.

**Comment by PatrykMatyjasek** [comment] 2015-07-14 07:19
Verified on 0.2+b1-7-g4cd8932 but still reproducing.

**Comment by krzycz** [comment] 2015-08-25 20:18
The patches we cherry-picked from upstream do not fix all the problems. *Jemalloc* will do its best to shrink the allocation in-place when possible. But it won't work in all the cases (by design), and it can't be fixed.

**I suggest to relax the test criteria** - reallocation (to the smaller size) should succeed if only there is at least one free chunk (4MB) in the pool, regardless of the old and new allocation size.
Otherwise, close this issue as FAD/NTBF.

In theory, we could define some safety margin in *libvmem*, that prevents allocating all the available memory space, and reserve one chunk (or some percent of the usable pool space) for the purpose of *realloc*. Then, we could (probably) guarantee that reallocation to the smaller size will always succeed.  But I'm not sure if it's worth the effort.

**Comment by krzycz** [comment] 2015-12-28 11:10
Yet another idea how to fix that...
If *libvmem* is not able to shrink the allocation in place and there is no space to make a new allocation, we can simply return the pointer to the original allocation. Still better than NULL.
Also, in case of huge allocations that are larger than 4MB (chunk size), we can at least resize it to a single chunk (in place), possibly releasing some memory.

**Closed** 2016-01-14 13:22 UTC
Labels: Exposure: High, Priority: 3 medium, Type: Bug
