### ISSUE TITLE
vmem: vmem_realloc(valid_pool_pointer, NULL, 0) returns NULL ptr and errno=12 (out of memory)

### ISSUE THREAD

**Issue by hubertsoltysiak** [pmem/issues#25] opened 2015-01-21 15:00 UTC
Reallocation NULL pointer using vmem_realloc(valid_pool_pointer, NULL, 0) returns NULL ptr and errno=12 (out of memory).

Steps to reproduce:
1. create valid vmem pool: vmp = vmem_create("/mnt/psmem", VMEM_MIN_POOL);
2: Reallocate memory using vmem_realloc(vmp, NULL, 0);

Expected result:
ERRNO=0, returned value is valid pointer - function should behave like vmem_malloc as manual states

Actual result:
NULL ptr is returned, errno=12 (out of memory)

**Comment by donaldematthews** [comment] 2015-02-11 03:05
My testing so far reveals that the vmem_realloc(vmp, NULL, 0) operation works fine, returning a valid pointer, not NULL.

**Comment by donaldematthews** [comment] 2015-02-11 03:17
Here is the test program I used:

//
// To build:  gcc -g vmem_realloc_test.c -o vmem_realloc_test -lvmem -lpthread
// To run:    ./vmem_realloc_test
//
#include <stdio.h>
#include <fcntl.h>
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <libvmem.h>
#include <libpmem.h>

int main()
{
    size_t pool_size = (size_t)14*1024*1024;
    size_t alloc_size = (size_t)8*1024*1024;
    size_t realloc_size = (size_t)4*1024*1024;
    VMEM *vmp;

    vmp = vmem_create("/mnt", pool_size);

    if (!vmp)
    {
        printf("cannot create pool\n");
        return 1;
    }

    int *allocation[2];

    allocation[0] = vmem_realloc(vmp, NULL, 0);
//  allocation[1] = vmem_realloc(vmp, allocation[0], 1);
//  allocation[1] = vmem_realloc(vmp, allocation[0], realloc_size);

    if (allocation[0] == NULL)
    {
        printf("vmem_realloc() failed\n");
    }

    printf("Done\n");

    vmem_delete(vmp);

    return 0;
}

**Comment by donaldematthews** [comment] 2015-02-11 14:45
Looks like my test code got mangled pretty badly when I pasted it into this web site, so I can send it via e-mail if necessary.  But I think you can still get the basic idea of what I did.  If I can do something different that will reproduce the bug, please let me know.

**Comment by paul-von-behren** [comment] 2015-02-11 17:16
Your code sample is now readable.  Github uses a (sort of) markup language called markdown.  If you type in three backticks on a line, then paste code, then add a line with 3 backticks, github will treat it a code snippet. I'm not sure how to express this visually :-( 

Here's a good starting point for markdown: https://help.github.com/articles/markdown-basics/

**Comment by krzycz** [comment] 2015-02-11 20:30
IMHO the problem description is not complete.

Try to do the following steps:
- create the vmem pool
- allocate all the available memory (i.e. invoking `vmem_malloc(256)` in a loop until you reach OOM and got NULL returned)
- then call `vmem_realloc(vmp, NULL, 0)`

Hints: 
1) According to spec, `realloc(NULL, size)` is equivalent to `malloc(size)`, so `realloc(NULL, 0)` is equivalent to `malloc(0)`.

2) In *jemalloc,* `malloc(0)` is internally converted into `malloc(1)`. 
Why? Because it's hard to return a pointer to something that doesn't exits (zero-length buffer) _AND_ provide that such pointer is unique. (I mean - it's not really hard, but it complicates the design/implementation of the library).
The spec says that `malloc(0)` _may_ either return NULL, or a valid (unique) pointer, that may be later passed to `free().` It's implementation dependent, but seems like most of the memory allocator libraries do the latter. So, the *jemalloc* does.

3) In practice, *jemalloc* does not allocate just 1 byte, as (AFAIR) the smallest allocation (smallest *size class* in *jemalloc*) is 16 bytes (internally).

And that's the answer why it fails - to "allocate" zero-length buffer it actually requires to allocate 16 bytes. But this may require to allocate a new 4MB chunk, to start a new run of 16B buffers (if there was no other 16B allocation before). But if all the pool memory is already allocated, such chunk allocation (and in consequence, zero-length allocation) will fail.

To confirm this is the right hypothesis, try to add an additional step to the above repro sequence - right after creating the pool, allocate just one buffer with size=0 or 1 (just to start a new run of 16B allocations). Then run the sequence of vmem_malloc's of another size class (say 256) until OOM, and then try to do `vmem_malloc(vmp, 0)` or `vmem_realloc(vmp, NULL, 0).` In this case, it will succeed, I suppose. And probably some number (~65000) of successive zero-sized malloc's/realloc's will also succeed (until we consume the entire 4MB chunk). 

After all, I'm not sure if this is a real issue/bug - maybe it's an expected behavior? Maybe we should just state is clearly in the man page?

**Comment by donaldematthews** [comment] 2015-02-18 20:42
Thanks, Krzysztof, but it doesn't appear to work exactly like you anticipated it would (described above).  I created a pool, then allocated all the memory in it (i.e. looping until the returned pointer was NULL), then did the vmem_realloc(vmp, NULL, 0), and that succeeded.  You indicated above that it should fail.  I also replaced that last operation with a vmem_malloc(vmp, 0) and it also succeeded.  I'm not sure where we want to go with this from here.  Please advise.

**Comment by donaldematthews** [comment] 2015-02-18 20:46
Here is the test program I used:

```
//
// To build:  gcc -g vmem_realloc_test.c -o vmem_realloc_test -lvmem -lpthread
// To run:    ./vmem_realloc_test
//
#include <stdio.h>
#include <fcntl.h>
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <libvmem.h>
#include <libpmem.h>

int main()
{
    size_t pool_size = (size_t)14*1024*1024;

    VMEM *vmp;
    int  *ptr;

    vmp = vmem_create( "/mnt", pool_size );

    if( !vmp )
    {
        printf( "cannot create pool\n" );
        return 1;
    }

    do
    {
        ptr = vmem_malloc( vmp, 256 );
    }   while( ptr );

    ptr = vmem_realloc( vmp, NULL, 0 );

    if( ptr == NULL )
    {
        printf( "vmem_realloc()failed\n" );
    }

    printf( "Done\n" );

    vmem_delete( vmp );

    return 0;
}
```

**Comment by krzycz** [comment] 2015-02-19 13:30
Well, in practice *Jemalloc* internals are more complicated than I described.

*Jemalloc* does not allocate a new chunk for each class size (i.e. separate chunk for 16B allocations, and another for 256B). A single chunk may hold allocations of different sizes, and they're organized in so called *runs*. If there is no run of given class size, or if all the blocks in given run are allocated, then an unused part of a chunk is reserved for a new run. And only if there is no space in given chunk to create a new run, then a next chunk is allocated.

The *run* size may vary depending on the class size. I.e. for 8B or 32B allocations, the run is just one 4K page, so it may hold ~500 or ~125 blocks of given size respectively (assuming some amount of memory used for metadata). But if the block size is 256B, then such a 4K run could hold only ~15 blocks, so it seems to be reasonable to increase the run size for larger size classes. And in fact, for 256B, the default run size is 16K.

So, what happens if you allocate 256B blocks in a loop? 
On the first *malloc*, the library will allocate a new 4MB chunk, and reserve 16K of it for a new run of 256B blocks. After ~63 iterations, such *run* will get out of space, so another 16K run will be reserved for the next run, and so on...
After ~16000 allocations (~256 runs), we'll get out of space in the current chunk, and the next 4MB chunk will be allocated. And the next ~16000 blocks of 256B can be allocated.

And that's it for a 14MB pool - no more chunks are available. 
Since the base address and size of each chunk must be 4MB aligned, then the first 4MB is wasted for pool metadata (pool header), as well as the trailing 2MB. So, there are actually only two usable chunks (8MB).

If you add a counter to your code, you'll see that the actual number of allocated blocks (256B) is about 32000, as expected.

But why subsequent `realloc(NULL, 0)` or `malloc(0)` succeeds?
Because even if there is no space in any chunk for another 16K run of 256B blocks, there might be still a space for 4K run(s) of smaller blocks (i.e. 8B). And in fact, it seems like in case of our example, there is still 8K of free space in each chunk, which means 2 runs in each chunk. As each 4K run may hold ~500 allocations of 8B, we can still allocate ~2000 blocks of 8B (this is the smallest block that can be allocated in *jemalloc* - `malloc(0)` or `malloc(1)` are equivalent to `malloc(8)`).

And again, if you repeat the `vmem_realloc(vmp, NULL, 0)` in a loop, you'll see that it will fail after ~2000 iterations.

Then change the allocation size from 256 to 32. 
Now, `vmem_malloc(32)` will fail after ~255000 iterations. But subsequent `vmem_realloc(vmp, NULL, 0)` will also fail, as if there is no space for 4K run of 32B blocks, there is also no space for 4K run of 8B blocks...

**Comment by krzycz** [comment] 2016-01-20 16:55
After all, I think it's time to close this issue.
Since, `vmem_malloc(vmp, 0)` and `vmem_realloc(vmp, ptr, 0)` may actually allocate some small amount of memory, same as their `malloc/realloc` equivalents, it is not surprising that in some scenarios such calls may fail due to out-of-memory condition. It cannot be considered a bug in *libvmem*, but rather the expected behavior.

**Closed by krzycz** 2016-01-20 16:55 UTC
Labels: Exposure: Medium, Priority: 4 low, Type: Bug
